# Generated by Django 2.2.5 on 2019-09-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_api', '0003_news_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
