# Generated by Django 2.2.5 on 2019-09-26 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_api', '0004_auto_20190925_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=256)),
                ('photo', models.CharField(blank=True, max_length=256)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='social_api.Profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
