# Generated by Django 2.2.5 on 2019-10-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_api', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
